/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    IconEpStar: typeof import('~icons/ep/star')['default']
    IconEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    MVPBadges: typeof import('./components/MVPBadges.vue')['default']
    MVPFeature: typeof import('./components/MVPFeature.vue')['default']
    MVPFeatures: typeof import('./components/MVPFeatures.vue')['default']
    MVPGitalk: typeof import('./components/MVPGitalk.vue')['default']
    MVPLayout: typeof import('./components/MVPLayout.vue')['default']
    MVPPlugins: typeof import('./components/MVPPlugins.vue')['default']
    MVPVisitor: typeof import('./components/MVPVisitor.vue')['default']
  }
}
